[project]
name = "api-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=33.3.0",
    "flask-jwt-extended>=4.7.1",
    "flask>=2.2.3",
    "pandas>=1.1.1",
    "pymysql",
]
